### ISSUE TITLE
Nuclear power plant model

### ISSUE THREAD

**Issue by briligg** [briligg/moonwards#2]
_All of the models are being posted for ongoing input to their design. This is first draft level work. Any input regarding them is welcome. This initial post in this thread will be updated as the model changes. All models are available as part of the *CP-MissionX-Master.blend.zip* files, where X is the mission number. Right now only mission 3 is available._

![ntr1000](https://cloud.githubusercontent.com/assets/5508441/14406199/5b33a05c-fe66-11e5-8108-52e8dfd79d5c.jpg)

It has been placed at the bottom of a crater about 500 m from the colony, where the microwave transmitters at the top of the mast with the radiators have a view of all the equipment, while the generator itself is below the crater rim, out of the line of sight. A microturbine design needs to be adapted for a closed-loop system that uses the reactor as its heat source.

**Comment by SigvartBrendberg** [comment]
How is the radiator equipment for that thing?

**Comment by briligg** [comment]
I put in a cable-supported tower that has both the radiator panels and the microwave power transmitters on it in the little mock-up i've done. Because it uses air cooling and combustion of a fuel, i'm not sure how useful the reference image of a micro-turbine is. I could perhaps look for something better.
