### ISSUE TITLE
Make links to individual models for download?

### ISSUE THREAD

**Issue by SigvartBrendberg** [briligg/moonwards#27]
It would be nice to link some individual models for download, perhaps under "project" so they are easier to find than navigating the repo.

**Comment by briligg** [comment]
Oh - just saw this. So this is why you mentioned that GitHub can be used like social media :)

Maybe you are right. I sort of expected someone who wants to get involved like that to check the repo and understand how to use it. One thing this maybe implies is that the listing of those files should be made more user friendly. 

They are also all available for download at SketchFab.

**Comment by SigvartBrendberg** [comment]
Yeah, the repo should really be good enough for this. Not really a problem.
