### ISSUE TITLE
RSS feed capacity to include links

### ISSUE THREAD

**Issue by briligg** [briligg/moonwards#30]
The most recent post 022.html, was meant to include two further links besides the one the title linked to. Currently the body of a post will not accept formatting for a web address. This is a low priority, but it would be nice to be able to add other links.

**Comment by SigvartBrendberg** [comment]
I see, it automatically escapes them at build time to stuff like "&lt;a href=&quot;".

**Comment by SigvartBrendberg** [comment]
And Github automatically unescapes that :D

**Comment by SigvartBrendberg** [comment]
Well, HTML is not valid XML, so we can not remove the escape filter in the liquid markup directly. But XML supports arbitrary character data inside <![CDATA[]]> tags, so wrapping it in that fixes the problem.

**Comment by briligg** [comment]
Works for the rss feed in a reader, but not for how it is displayed on the homepage.

**Comment by briligg** [comment]
Update to sigfeed.html has fixed problem. Thanks Sigvart
