### ISSUE TITLE
Content: make an app for common orbital properties

### ISSUE THREAD

**Issue by briligg** [briligg/moonwards#31]
I've had to do this so much, i want to make a Geogebra or canvas app that works with sliders and input fields to calculate orbital velocity and gravity, based on a slider for mass of primary and altitude. Or maybe it should be a canvas app.

**Comment by SigvartBrendberg** [comment]
first version in GeoGebra/velocity_app. Proper canvas app later.

**Comment by briligg** [comment]
Thanks, Sigvart.

**Comment by briligg** [comment]
Ok, playing with it, i see what i mean is it needs sliders for radius of primary, altitude, and mass or gravitational parameter - i find using gravitational parameter a bit hard to get used to, but i guess i just need to use it a bit. And the gravitational parameter slider needs to go from 1 to 1000, where each number is multiplied by 1E+12. And the radius should go from 1 to 10, where each number is multiplied by 1E+06. And i looked for how to adjust that in Geogebra but didn't find it. Might get to looking at a tutorial on the weekend.
