### ISSUE TITLE
JS to make details load expanded if loaded from a permalink

### ISSUE THREAD

**Issue by briligg** [briligg/moonwards#32]
The Timeline page has a very large number of sections and subsections, far too many to put in a menu. To make it easy to navigate the page, i've used details tags to create a large number of sections that can be expanded. 

However, this means that if someone wants to share something in particular on the page, when someone comes to the page from that link, the section isn't visible, they have to expand it. And that means there are a large number of subsections that can't be linked to at all. 

I have an idea it wouldn't be hard to make a short script that makes them load expanded if the permalink is what is loaded. However, i'm just guessing there. It's a thought.

**Comment by SigvartBrendberg** [comment]
Script written.
It checks if the url has an id in it, and then expands all <details> tags withing that <article>
For some reason git had a large diff in history, so sorry if I messed up the repo.

**Comment by briligg** [comment]
Thanks, Sigvart. 
Yes, that diff is very odd. For me as well, it is downloading a huge amount of stuff. I don't understand, i'll try to look into it.

**Comment by briligg** [comment]
MolbOrg says he has a script to fix this problem, and some maintenance check scripts. He'll add them to the repo. I don't think anything has changed on my system that would have caused me to push the previous history, but i can't be sure. Right now, i'm just inclined to get it fixed and not think about it too much.
