### ISSUE TITLE
Add permalink icons to each heading in the timeline page

### ISSUE THREAD

**Issue by briligg** [briligg/moonwards#33]
There should be a link icon in the narrow margin to the left of each heading.There is probably a Unicode symbol for that. Clicking that icon should load the internal link to that heading so it can be easily shared. 

I'm reminding myself here to do that once i've finished rewriting the main pages of the website to be up to date with the timeline. That takes priority right now.

**Comment by SigvartBrendberg** [comment]
🔗
&#x1f517;
U+1F517

**Comment by SigvartBrendberg** [comment]
I say this we implement this with client side js as that is relatively straight forward to do. I can write the script, but then each \<details> section needs its own id so it is possible to link to it. That affects [issue#32](https://github.com/briligg/moonwards/issues/32) as that script must then also handle individualy linked \<details> sections and not just \<article>.

If you take id labelling I can make the rest work

**Comment by briligg** [comment]
Ok, that sounds great. I wasn't sure how busy you are so i didn't want to get into implementation of issue#32. I was having trouble making it work. 

This could also handle the issue that the menu bar is on top of the rest of the page, and so when an internal link is loaded, it is behind the menu and is invisible.

**Comment by SigvartBrendberg** [comment]
Ok, I have now written a script that adds a permalink button to each \<details> tag that has an id. It generates a textarea with the link when clicked. The button gets the class "permalink", so you can use that as a css hook to make it look clickable and pretty :)

**Comment by briligg** [comment]
It's working, but gives an incomplete address. It doesn't have the 'https://www.moonwards.com part. It is live on the site now.

**Comment by SigvartBrendberg** [comment]
local urls and server urls are different things... I see...

**Comment by SigvartBrendberg** [comment]
Should be fixed now. It's not like testing is important or anything :)

**Comment by briligg** [comment]
Awesome. Um, there are two slashes between 'moonwards.com' and the rest. I looked at the code but i'm not sure how to fix it. I guess the `* '/' +` isn't necessary?

**Comment by SigvartBrendberg** [comment]
Again this testing thing...

**Comment by briligg** [comment]
I can test. That's okay.
